#!/bin/sh

#
#    jnettop, network online traffic visualiser
#    Copyright (C) 2002-2005 Jakub Skopal
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#    $Header$
#

# This is an example script doing IP lookups thru SAMBA name servers. It either returns
# name resolved from the appropriate IP address or nothing if no name is found.

nmblookup -A $1 | sed -n '
1 d
2 {
    /^\t/ {
		s/^\t\([^ ]*\) .*/\1/
		p
	}
   }
'

